name: Build and deploy nflow nuget

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout source from @main
        uses: actions/checkout@main

      - name: Setup .NET sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --no-build --configuration Release --blame --results-directory ./artifacts/tests

      - name: Package libs
        run: find 'lib' -maxdepth 2 -mindepth 2 -not -path '*tests*' -exec dotnet pack --no-restore --no-build --configuration Release --include-symbols --output artifacts/nupkgs {} \;

      - name: Push packages
        run: find artifacts/nupkgs/*.nupkg -exec dotnet nuget push {} --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json \;
